# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fernando Greve
email: fgreve@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal webpage for an aspiring data scientist.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fgreve.github.io" # the base hostname & protocol for your site
twitter_username: f_greve
github_username:  fgreve
linkedin: https://www.linkedin.com/in/fernando-greve-36235217/

# Build settings
markdown: kramdown

# Fix “No repo name found”
repository: 'fgreve/ffgreve.github.io'